-- MySQL Script generated by MySQL Workbench
-- 2016年04月26日 星期二 14时42分55秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`er_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`er_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` CHAR(40) NOT NULL DEFAULT '',
  `userpass` VARCHAR(30) NOT NULL DEFAULT '',
  `articlenum` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户发表文章数目',
  `score` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户的积分',
  `level` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户的等级，对应一个等级表，当用户的积分达到一个限度的时候，获得更高的等级',
  `follower` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户追随的其他用户数量',
  `followered` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户被其他用户追随的数量',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '这是一个用户表';


-- -----------------------------------------------------
-- Table `mydb`.`er_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`er_admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adminname` CHAR(40) NOT NULL COMMENT '管理员的名字',
  `adminpass` VARCHAR(30) NOT NULL COMMENT '使用md5加密',
  `logintime` INT NOT NULL DEFAULT '',
  `lock` TINYINT NOT NULL DEFAULT 1 COMMENT '默认1为未锁定，0则为锁定',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`er_cate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`er_cate` (
  `id` INT NOT NULL,
  `catename` CHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`er_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`er_articles` (
  `aid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aname` VARCHAR(20) NOT NULL,
  `content` TEXT NOT NULL,
  `cate` CHAR(20) NOT NULL DEFAULT '' COMMENT '所属分类',
  `readnum` INT NOT NULL COMMENT '阅读量\n',
  `summary` VARCHAR(255) NOT NULL COMMENT '文章简要',
  `createtime` INT NOT NULL COMMENT '发布时间',
  `commitnum` INT NOT NULL DEFAULT 0 COMMENT '评论数',
  `pic` VARCHAR(40) NOT NULL COMMENT '背景图片的路径',
  `zannum` INT NOT NULL DEFAULT 0 COMMENT '点赞数\n',
  `author` CHAR(40) NOT NULL,
  `er_cate_id` INT NOT NULL,
  PRIMARY KEY (`aid`, `author`, `er_cate_id`),
  INDEX `fk_er_articles_er_user1_idx` (`author` ASC),
  INDEX `fk_er_articles_er_cate1_idx` (`er_cate_id` ASC),
  CONSTRAINT `fk_er_articles_er_user1`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`er_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_er_articles_er_cate1`
    FOREIGN KEY (`er_cate_id`)
    REFERENCES `mydb`.`er_cate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`er_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`er_comment` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `commentcont` VARCHAR(255) NOT NULL COMMENT '评论内容',
  `commentzannum` INT NOT NULL COMMENT '点赞数',
  `er_articles_aid` INT UNSIGNED NOT NULL COMMENT '关联文章的aid\n',
  `commentauthor` CHAR(40) NOT NULL COMMENT '发布评论的作者',
  `createtime` INT NOT NULL DEFAULT '' COMMENT '评论的发布时间',
  PRIMARY KEY (`cid`, `er_articles_aid`),
  INDEX `fk_er_comment_er_articles1_idx` (`er_articles_aid` ASC),
  CONSTRAINT `fk_er_comment_er_articles1`
    FOREIGN KEY (`er_articles_aid`)
    REFERENCES `mydb`.`er_articles` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`er_followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`er_followers` (
  `followerid` INT NOT NULL AUTO_INCREMENT,
  `followeruserid` INT NULL COMMENT '追随者对应的id\n',
  `er_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`followerid`, `er_user_id`),
  INDEX `fk_er_followers_er_user1_idx` (`er_user_id` ASC),
  CONSTRAINT `fk_er_followers_er_user1`
    FOREIGN KEY (`er_user_id`)
    REFERENCES `mydb`.`er_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`er_followed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`er_followed` (
  `followedid` INT NOT NULL AUTO_INCREMENT,
  `followeduserid` INT NOT NULL COMMENT '粉丝的id\n',
  `er_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`followedid`, `er_user_id`),
  INDEX `fk_er_followed_er_user1_idx` (`er_user_id` ASC),
  CONSTRAINT `fk_er_followed_er_user1`
    FOREIGN KEY (`er_user_id`)
    REFERENCES `mydb`.`er_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
